### PR TITLE
Add Backing File format

### LINKED ISSUE #9: Create option should allow to specify format of the backing file
Backing file format comes under the `header extensions` section of the qcow image, it can be specified so that services such as `libvirt` can avoid probing for it.
It would be the equivalent of the `-F` switch in `qemu-img`. Here is [something](https://libvirt.org/kbase/backing_chains.html#importance-of-proper-backing-chain-setup) for its usage.

### PR DESCRIPTION
**Pull request by sswastik02**
Adds specification of backing file format header extension

closes #9

### CODE REVIEW

**Comment by sswastik02** [comment]
Hi @dypflying ,
I have made the necessary changes, Do let me know if anything else needs to be changed.

Thank you.

**Comment by sswastik02** [comment]
Hi @dypflying,
Just wanted to enquire if any changes are needed ?

**Comment by dypflying** [comment]
this looks good to me

**Comment by dypflying** [comment]
> Hi @dypflying, Just wanted to enquire if any changes are needed ?

Sorry for the late reply, no any other changes needed here, I'm merging the PR

**Pull request merged**
